import React from 'react'
import './AllChapters.css'
import ChapterFooter5 from './ChapterFooter5'




function Chapter5() {
  return (
    <div className='rap'>
          <div>
        <h1>CHAPTER 5</h1>
        <h2> Breakout</h2>
        </div>
        <p>
        ALEX KNEW THERE WAS no way out of the cell. It was buried as deep in the mountain as it was possible to be. There was no window. But for the single bulb burning over his head, he would have been in the pitch-dark. The door was a piece of solid wood, ten inches thick. Alex had measured it when he was led in. He had also noticed the two iron bars that would slide across on the outside. If he’d somehow gotten his hands on a pile driver or a battering ram, it wouldn’t have done any good. And Alex had nothing. All his equipment had been taken away from him. He was dressed in loose army combats and sandals. The cell had a bunk, a table bolted to the floor, and a plastic jug of water. Darcus Drake was taking no chances.

At sunset, he was going to be tied to a stake and shot. Alex tried to force the image out of his mind. He was scared but he wasn’t going to let fear weaken him. They still had to lead him from this cell, up two flights of stairs, and through the main chamber to the stone platform outside, and somewhere along the way, an opportunity would arise. All it needed was one guard to make one mistake. Perhaps the man in the white van—Farshad—was looking for him. After all, he had seen Alex taken prisoner. And what of Rafiq and the other tribesmen waiting for him in the cemetery? They would soon realize that something had gone wrong and they might try to help. Something would turn up. And Alex would be ready.

That was what he thought, but as the day wore on and he was left alone for hour after hour, he had to fight for control. He had no watch. He had no idea how much time was passing, how close he was to sunset. He kept himself active with push-ups, counting to fifty before he allowed himself a rest. He paced from one wall to the other—six paces there and back—until he could do it blindfolded. He sipped a little of the water. Nobody came with any lunch. He guessed that Drake was doing this on purpose. He wanted Alex to look worn-out and defeated when he was taken to his execution. It would look better on film.

Three hours, four hours, five hours . . . Alex guessed it was close to midday when he heard a sound outside the door, metal scraping against wood. He had been resting, lying on the bunk, when it happened, and his eyes flicked open, instantly alert. Someone was drawing back the bars. Had they come for him already? He expected the door to open. It stayed shut, but Alex was already on his feet, crouching down beside the wood, listening for any sound in the corridor outside. He heard soldiers march past, their boots stamping on the ground. Then silence. He reached up and grabbed hold of the iron ring that served as a door handle. He pulled. The door opened.

Looking out, he saw that the corridor was empty. Alex was puzzled. What was going on? Was this some sort of test? Was Drake playing a trick on him? He wasn’t going to waste time wondering about it. This was the opportunity he had been waiting for. He slipped outside and found himself in a dungeon area with stone walls and doors. He watched the soldiers—there had been four of them—disappearing into the distance and tried to work out his next move. He already knew that even if he was out of the cell, he wasn’t out of trouble. Drake had told him there were two hundred men at the citadel. He was high up in the Herat Mountains with a dizzying fall from the edge of the stone platform. The only way out was through the portcullis with the track beyond, but that would be heavily guarded. And if he did make it out of Falcon’s Edge, where would he go next? The Shuja cemetery was about twenty miles away, the Iranian border a lot farther. He was on his own. As relieved as he was to be out of the cell, Alex knew that his position was almost hopeless.

He watched the guards go, then went in the opposite direction. There were just a few steps until the passageway came to a corner, and as Alex reached it, a man suddenly appeared, walking toward him. With a shock, Alex recognized Faisal, the Kochi tribesman who had betrayed him in the first place. Faisal opened his mouth, about to call out, but Alex was already moving, running forward and lashing out with the front kick—mae geri—that was one of the first moves he had learned at karate. Alex was half the size of the man he was attacking, but that didn’t matter . . . He had chosen his target carefully. The ball of his foot slammed into Faisal’s solar plexus, knocking the wind out of him in one sharp breath. He followed through with a vicious back fist strike, targeting the man’s throat. Faisal crumpled. Both his eyes had gone white, although, of course, one of them had been that way already.

Which way? Before Alex took off, he reached down and removed the shemagh—the Afghan scarf—that Faisal had been wearing, winding it over his head and around the lower part of his face. In a way, Drake had done him a favor. By making him change his clothes, he had made him invisible . . . Now he looked like everyone else. He continued forward, leaving the unconscious man behind. He knew which way he had been brought here. He just had to retrace his steps and find a way out before Faisal—and the empty cell—was discovered.

He came to an old-fashioned lift. As he arrived, the gate opened and a chef came out, a man in a grubby white jacket, carrying some sort of skinned animal, perhaps a goat. There was no time to hide, and Alex knew that any hesitation would finish him. He kept his head down. Half his face was concealed. Without breaking his pace, he brushed past the man and went into the lift. As he had hoped, the man had his mind on other things and didn’t even notice him. Alex pressed the top button and heaved a sigh of relief as the door slid shut.

He was carried upward. The lift seemed painfully slow, and Alex was already worrying about what he would see when the door opened again. In fact, he came out in an area behind the calutron, and now he was doubly glad that the complicated machine wasn’t working. There was nobody in this part of the complex. Alex hurried around the edge. Part of him was already planning what to do next, but at the same time he was also thinking back to the cell. Who had opened the door? Was there something he was missing? It occurred to him that he might have a friend somewhere in Falcon’s Edge. After all, someone had opened the cell door. But if so, where were they and what had happened to them?

He was almost back where he had started. The main storage area was still a mass of activity with at least fifty soldiers moving around, going about their duties, all of them armed. The three supply vans had left. Alex sneaked farther into the chamber and hid behind one of the crates. It was attached to a parachute, and he drew the silk fabric toward him, using it to conceal himself. The outdoor platform where he was to be executed was right in front of him. He could actually see two men setting up a camera and a tripod. It made him feel sick that anyone could think of making a film like that, and he certainly had no intention of being its star. But how was he going to get out of here? The portcullis was the only way. If it was open and if he moved fast enough . . . But he still had to cross the plain, twenty miles or more. The moment they knew he was free, they would come after him. Stealing a jeep was out of the question. Even if Alex had known how to drive, he doubted they’d have left the keys in the ignition. Was there another way?

He remembered the horses. They were still tethered to the railing, three of them, sturdy and fast, by the look of them. Alex hated riding, but at least they didn’t need keys! The horses already had saddles and bridles. They were ready to go. Crouching beside the crate, measuring distances, Alex tried to work out a plan. He had no doubt that he could reach the horses without being seen. Everyone was too busy to notice him. It was when he mounted up and began to ride that his problems would begin. The alarm would be raised and they would either shoot him or shoot the horse. If they lowered the portcullis—and that would be the first thing they would do—he would be trapped. He needed the element of surprise. But how?

The idea came to him so suddenly that he almost gasped. It was impossible! It couldn’t possibly work. But he was alone, surrounded by an entire army. He was going to be executed in a few hours’ time. What other choice did he have?

He started at once. If he thought about this, even for a second, he wouldn’t go through with it. It was early afternoon and the sun was at its hottest. That helped. A lot of Drake’s men were unfocused, wishing they could have a siesta. They didn’t notice the extra soldier making his way around the side of the cavern, carrying a bundle in his arms. Nor did they notice when he picked out one of the horses and got to work. The horse protested, snorting and stamping one of its hooves, but nobody came over. Alex was closer to the platform now and took stock of his surroundings. The camera was ready. Three more men were positioning a wooden stake in the ground, right next to the wall. That was for him. But Alex was grimly determined. Whatever happened, whether he lived or died, he wasn’t going to play their game. He would go out fighting. He just wished he had been able to grab one of the AK-47 machine guns. Falcon’s Edge was jammed with weapons of one sort or another. He was probably the only person in the entire place who was unarmed.

Alex’s heart was thumping and there was a hollow in his stomach as his entire being recoiled at the thought of what he was about to do. A group of soldiers walked past and he leaned down, pretending to busy himself with the horse he had chosen, in fact concealing himself behind it. He waited until they had gone. It was now or never. Once he climbed onto the horse, someone would be bound to see him. He couldn’t hesitate, not for one second.

And then the alarm went off.

Someone must have discovered the unconscious man—either that or they had come to check on him in the cell and found that it was empty. The alarm was not a bell. It was a siren that tore through the air, screaming its urgency. Well, that might help him too. For a moment everyone was confused, wondering what the fuss was about. Alex untethered the horse. At the last moment, he noticed a riding crop on the floor and snatched it up, knowing he would need it. Even as he steadied himself in the saddle, he felt the horse resisting. That was the whole secret of riding, that sense of understanding between the horse and its rider. Well, this horse would have realized at once that this Rider was not in control. It didn’t matter. Alex was desperate. Somehow he would get the animal to do what he wanted.

He jerked on the reins and wheeled around. At the same time, the scarf slipped and somebody cried out. They had seen him! Alex dug in his heels and for good measure lashed out with the crop. If the horse didn’t move, they would both get killed. Sure enough, there was a shot and a bullet ricocheted off the stone wall above their heads. The sound of it frightened the horse more than Alex had managed. He was almost thrown off as the animal reared up. Alex heard a second shot and felt a bullet pass inches over his shoulders. Everything was happening at the same time. He felt the cavern spin around him. There were men running toward him. The siren was still blasting at full volume. The horse’s front hooves made contact with the ground and then the two of them were off.

They were going the wrong way! The horse had set off at a gallop, but it was heading back into the cavern, toward the jeeps and the helicopter. Alex pulled frantically on the reins and wheeled the horse around. He heard a series of shots and the windows of the jeep right behind him shattered, the glass crashing down. The sunlight was straight ahead of him. There was the stone arch of the cavern, then the stone platform, and then, if he kept going, a drop of three hundred yards to the plain below. The gate with the portcullis was off to the right, but the guards were already ahead of him. At least ten of them had grouped together to block his way. They were all armed, waiting for him to ride toward them.

Alex wasn’t stopping now. With a yell, he whipped on the horse, propelling it out of the cavern and into the light. The soldiers were firing at him. He could feel the bullets scorching the air all around him. At this range, they shouldn’t have missed, but perhaps they were trying to hit him, not the horse, and anyway, they had miscalculated—he wasn’t riding toward them, he was going straight ahead. They stopped firing. There was no need to waste any more bullets. It was clear to them that Alex was committing suicide. He was heading straight toward the edge of the platform and the sheer drop beyond. Ten yards, five yards, three yards . . . Alex covered the ground in no time at all. Out of the corner of his eye he saw the metal gate crashing down to block the archway and, nearer to him, the execution post, the waiting camera. He ignored them. He had made his decision. It was happening now.

The horse sensed what he wanted, but only when it was too late. Alex whipped it one last time, hating what he was doing, knowing there was no other way. The soldiers stared. The horse screamed. The edge came rushing up toward them. And then they had gone, launching themselves into space. At that moment Alex was only aware of a great stillness, the sun blazing, the plain so far below that shrubs and boulders appeared only as tiny specks. He felt the wind in his hair. There was a sense almost of calm and he thought that maybe this was what death is like.

But he wasn’t going to die. Not today. When Alex had crossed the cavern, he had been carrying the parachute that had been used to air-drop the crate. He had attached it not to himself, but to the saddle and to each end of the horse, running the cords under its legs. When he had ridden out, he had been trailing the canopy behind him, and despite the alarms and the gunfire, his greatest fear had been that it would catch on something and tear. He had been lucky. The parachute had been intact as he urged the horse over the edge. The moment they cleared the platform, it was dragged upward, opening out. It was above them now. It had formed itself into a fantastic flower, shading them from the sun. And the two of them weren’t falling anymore. They were floating down.

It was a fantastic sight. The horse was terrified, its eyes bulging, its legs flailing as if it were galloping through the air. For his part, Alex was clinging on for dear life, too afraid to look down, vaguely aware of the cords stretching past him and the white silk billowing over his head. The parachute had taken their combined weight with ease. They were heading down toward the plain, at the same time being swept ever farther away from Falcon’s Edge. Alex risked a glance back and saw the soldiers on the platform, already miniature. One or two of them were shooting at them—he saw the flash of an AK-47—but they were well out of range. Apart from the rush of the breeze in his ears, everything was silent. Even the horse seemed to have stopped panicking. Gently, they wafted down.

The next time Alex looked, the ground was rushing up toward them, far faster than he would have expected. He tensed himself, waiting for the landing—but already he knew that he had been lucky. He had rigged the parachute perfectly. If the cords hadn’t been evenly divided, the horse could have tilted backward or forward and the two of them might have hit the ground as a twisting ball of animal and boy. Everything depended on the next few seconds. Alex had taken the horse with him because it wasn’t enough to break out of the citadel. He also needed to be moving at speed. He had no doubt that once they had recovered from the surprise, Drake and his men would be after him.

This was the moment of truth. Once again the horse was pedaling as if it understood what was about to happen. Alex tightened his knees and squeezed the reins. There was a thud as the four hooves came into contact with the ground. The horse stumbled and Alex was afraid that it might have injured itself. But then it recovered and suddenly they were chasing across the plain, dragging the parachute behind. Alex couldn’t stop himself. Like a cowboy in the Wild West, he whooped with delight. He had done it! When escape had been impossible, he had made the impossible escape.

It wasn’t over yet. Behind him, the gates of the citadel opened. Three jeeps, with four men in each, came roaring out in pursuit.
        </p>
        < ChapterFooter5 />
    </div>
  )
}

export default Chapter5