import React from 'react'
import './AllChapters.css'
import ChapterFooter from './ChapterFooter'


function Chapter2() {
  return (
    <div className='rap'>
        <div className='chapter2'>
        <h1>CHAPTER 2</h1>
        <h2> In The Pipeline </h2>
        </div>
        <p>
        THE KOCHIS KNEW WHAT they were looking for, but even so, Alex was amazed that they had been able to find it without GPS or highly detailed maps. The entrance to the pipe network was a round hole set in a block of concrete, covered with thick steel wire. The whole thing was built into the side of a hill and half covered by rubble and wild grass. Even in broad daylight they could have walked past without seeing it, but they had come here in the middle of the night and they hadn’t even hesitated. The man called Usman cried out and beckoned them over. They set to work at once.

They had brought with them an oxy-acetylene torch and gas cylinder, strapped to one of the horses, and now they used it to burn through the wire. Alex watched the heavy strands as they glowed red and then peeled away. Part of him was afraid that the brilliant light of the cutter would alert someone that they were there, but as with the bonfire, the tribesmen showed no concern. They were surrounded by the great bulk of the mountains with nobody in sight. Falcon’s Edge itself was half a mile away and below them, tucked away in its own rockface. A passing satellite might notice the sudden glare, but by the time it had communicated the information to whichever intelligence agency controlled it, they would have been long gone. It was probably safe enough.

Alex found himself staring into the black, round hole that could have been the barrel of a gun, pointing straight at his head. He could just make out the curve of the pipe itself as it burrowed into the hillside, and the thought of crawling into it filled him with horror. Mrs. Jones had been right about one thing. Alex was slim and small for his age, but still, his shoulders would barely pass through and certainly no adult would be able to follow. He realized that once he began, it would be impossible to turn around. If the plans that he had been shown were wrong, if he came to a dead end, he would be trapped. Effectively, he was being asked to bury himself alive.

“Tomorrow.” Rafiq, the leader of the group who had brought him here, hadn’t dismounted from his horse. Glancing down at Alex, his face was full of doubt. “We meet . . . the Shuja cemetery.”

“Midday,” Alex said. Mrs. Jones had described the operation while he was in London. Getting out of Falcon’s Edge was going to be easier than getting in. If all went well, in less than twelve hours’ time, Alex’s work would be done and he would be escorted back across the border into Iran. If not . . . Alex didn’t like to think about the possibility of failure—and why should he? There were only about a hundred things that could go wrong.

Rafiq nodded. He took one look at the mad English boy who seemed determined to kill himself, then wheeled his horse around and rode away. The others followed him. Faisal, the man who was blind in one eye, twisted in his saddle and spat at the ground. It was as if that summed up everything he had to say about the adventure. He rode off, leading Alex’s horse behind him.

Alex was alone. Suddenly he felt very lonely, lost in the mountains. The wind was still gusting over his shoulders. He ran a hand through his hair, clearing it out of his eyes. Well, there was no point standing here having second thoughts. Right now, there was only one way back home.

He gathered his things together. Nothing that he was wearing was quite what it seemed. Derek Smithers, the ever cheerful, overweight science officer at MI6, had supplied Alex with all the gadgets he had needed on his last two missions, and he had equipped him for this one too. First, Alex checked the belt he was wearing around his waist. It was divided into various pockets, each one containing different items—weapons, medical supplies, maps, food, water—that he might need. The belt also had what looked like four suction cups, surrounding his body like points on a compass. Alex would need those later.

He had taken off the backpack. It would be impossible to fit into the pipe while he was wearing it. The backpack contained two batteries and a miniature computer, which would control all the equipment concealed in the combat suit. This extended to his hiking boots, which looked ordinary when seen from above but had two small glass plates concealed in the instep, in front of each heel. Finally, Alex slipped on a charcoal-gray helmet made out of some sort of impacted plastic. It wasn’t just there to protect his head. It housed a miniature digital camera, barely larger than a matchbox, that would record his journey through an opening one-sixteenth of an inch wide. Alex had been given a professional camera to photograph the calutron when he found it, but the helmet camera would act as backup. The helmet was also fitted with a Speleo Ultra Vario headlamp, powered by a built-in lithium ion battery. It was the lightweight, state-of-the-art flashlight favored by cavers.

He flicked it on and the beam shot out ahead of him. Alex directed it into the yawning mouth that waited to devour him. “The first part’s the worst part,” he muttered to himself. It was something Ian Rider had often said . . . helping him with his homework or teaching him to climb mountains. It was a joke between them because they both knew that the first part never was. It just got worse as it went along. Alex lowered himself onto his knees. He grabbed the backpack in both hands, took a deep breath, and plunged in.

The wind was cut off as if by a giant blade. The stars disappeared. He was completely surrounded by the smooth metal surface of the pipe. He could feel it pressing down on his shoulders, rubbing against his arms and legs. It seemed to go on forever. Looking ahead of him, he saw the light from his helmet cutting through the darkness, illuminating . . . nothing. There was just the pipe, a perfect circle glinting in the light, and him, the insect who had been foolish enough to crawl into it. He would have to worm his way along, pushing the backpack ahead of him. And suppose the diagrams that Mrs. Jones had shown him were wrong? Suppose the pipe narrowed? Alex put the thought to one side. There was no point wasting energy on problems until they became real.

He crawled forward, following the beam. It would be impossible to tell how far he had traveled, not when every section of the pipeline looked the same. Nor did he waste time checking his watch. He only knew that the farther he went, the more his elbows and knees, unused to bearing his weight, began to hurt. He also had to fight to stop himself from panicking. His brain was screaming at him to stand up, to turn around, to go back. But that was out of the question, he reminded himself. He had a job to do. He just had to focus on that. What would he do if the light went out? No. The lithium battery would last eleven hours and, in case of an emergency, he had a spare in his belt. Stop worrying about nothing. Alex knew perfectly well that the real danger was still to come.

A whole hour passed. At least, it felt like an hour. The pipe seemed to be getting narrower. Alex was sure he could feel it closing in on him. Was he imagining it or was it getting harder to breathe? He must have been about a quarter of a mile into the mountain and he could only imagine the thousands of tons of soil and rock bearing down on him from above. He stopped and forced himself to relax. A trickle of sweat slid down his face, finding its way through the crack between his helmet and the side of his head. It had been cold outside, but as he penetrated farther into the ventilation system, he began to feel the warm air being blasted up from somewhere far below. The deeper he went, the closer it seemed to get. He was also aware of a strange smell. It was mechanical, a mixture of oil and electricity.

He came to a T-junction. He had arrived before he knew it, almost hypnotized by the single beam of light. The second pipe, running left and right, was twice the size of the one he was in and he squeezed himself into it, feeling like toothpaste coming out of a tube. It was still pitch-dark but at least he no longer had the feeling of being trapped.

“You’ll be starting in one of the auxiliary outlets. It feeds into the main air shaft—and all I can say is that I’m glad they didn’t send me. I’m not sure I’d have gotten very far!”

It was Smithers speaking, his hands resting on his enormous stomach. Suddenly Alex was back at MI6, studying the charts and diagrams that were spread out in front of him. Mrs. Jones was in the room and there was another, thin-faced man who had been introduced as Orlov. He was the scientist who had worked on the calutrons and had come to British intelligence with the information.

“Once you get to the junction, you turn right. You’ll be able to move a little more easily. That’s the good news. But I’m afraid this is where your problems begin, old chap. You’re going to have to get through the exhaust fan.”

Alex could already hear it. The fan was whirring at high speed about fifty yards away. He felt the warm air rushing into his face. Alex grabbed the backpack and strapped it onto his shoulders. He was glad to have it behind him, out of the way. Then he started moving toward the next obstacle, supporting himself now with the palms of his hands. It was good to feel the space between his shoulders and the pipe as it curved over him. Briefly he wondered what had happened to Rafiq and the other Kochis. By now they should have worked their way around the mountains and onto the track leading down from Falcon’s Edge. Another two hours would bring them to the Shuja cemetery, named after a famous shah but in fact built by the British two hundred years ago for the soldiers who had died in the Anglo-Afghan War. Their instructions were to wait for him there, but Alex wondered if he would ever see them again. He hoped they were still owed money. Then they might stay.

Something flickered ahead of him. There were two silver struts coming down from the ceiling, joining together in a V, and they had reflected the light from the headlamp. The struts were part of a larger machine, a fan sucking up the stale air from below. It was blocking the entire passageway, turning so fast that the blades had become no more than a blur. The engine that controlled it was set behind the struts with a cable looping around. Even at a distance Alex could feel the power of the contraption. There was no way he would be able to stop it with his hand. He would simply lose the hand.

He continued forward until he was right up close, the breeze now battering his face and making it difficult to see. Automatically, he reached up to a special pocket, built into the breast of his jacket, and unzipped it. He drew out a rectangular box, black metal, about the size of a TV remote control. It had an antenna, which he unfolded, and a simple on/off switch. Alex pointed it in front of him, wondering even now if it would actually work.

The technology was simple even if it was still top secret. It had been developed by the US Air Force as part of CHAMP: the Counter-electronics High-powered-microwave Advanced Missile Project. How Smithers had gotten his hands on it, he preferred not to say. The box was a radar transmitter. Alex directed it toward the engine management system that turned the fan. He flicked it on. Instantly, the machine sent a series of magnetic pulses that traveled through the wiring loom of the fan system, confusing the electrics and causing the entire engine to shut down.

The fan came to an immediate halt. Alex was impressed, despite himself. Smithers had told him that one day the same technology could shut down an entire city, and now he believed it. Now he could clearly see each of the four blades, spaced out with enough of a gap for him to crawl through. He reached out to rotate them around so he could do just that.

If the creature hadn’t moved, he wouldn’t have seen it, and seconds later, he would have been finished. As it was, the beam of his headlamp reflected off some of its scales as they briefly twisted and that was what alerted him. He froze, his hand still outstretched, his mouth dry, his heart thudding against his chest. It was a snake and not just any snake. Crawley had shown him a picture during his briefing, just in case he happened to see one when he was crossing the desert. Alex recognized the ugly brown diamond shapes on its skin, the pear-shaped head, the oversized eyes. It was about twenty inches long . . . medium sized. Its Latin name was Echis carinatus, but it was better known as the saw-scaled viper. It was one of the most dangerous snakes in the world.

How had it gotten here? If the fan had been turning, it couldn’t have crawled through. Either the engine had been turned off, perhaps for general maintenance, or it had reached this section of the pipe from another direction. It had been asleep, but Alex had disturbed it and already it was uncoiling itself. It was making a loud hissing noise that didn’t in fact come from its mouth. It was rubbing its scales together to make the sound, preparing to strike. When it did so, it could travel three times farther than its own length. The fan wouldn’t stop it. The blades were too far apart. Even if Alex began to back away, it would still reach him. If it bit him, he would die. The saw-scaled viper has killed more people than any other species of snake, and he could already imagine it lunging at his throat, its fangs burying themselves in his flesh. After that, there would be a long, agonizing death. It might be months before his body was found.

How could he get past it? That was the next question. Alex knew that there was no other way around. If he turned back the way he had come, he would find himself alone in the Herat Mountains, and it was unlikely he would make it out of the country. But nor could he sit here hoping that the snake would simply go away. There didn’t seem to be any chance of that. The viper was angry, hissing louder, waiting for him to make his move. Alex remained perfectly still. One hand was on the propeller. The other, he realized, was still cradling the radar transmitter, and suddenly he knew what he had to do. It was all a question of timing. There really were going to be just microseconds between life and death.

Very carefully, he adjusted his hand, feeling for the on/off switch. All the time, he kept his eyes on the snake, almost willing it not to move. For its part, the snake stared at him with all the evil in the world. The hissing was more insistent, approaching the point of no return. It was about to strike. There could be no doubt of it. Alex weighed the transmitter in one hand. Then, quite deliberately, he slammed his fist into the side of the blade.

The snake believed it was threatened and leapt. It would have reached Alex before he could so much as blink, but it had to maneuver its way through the gap between the blades, and that slowed it enough for Alex to do two things. He threw himself backward, putting as much distance between himself and the snake as he could. At the same time, he flicked the switch that deactivated the transmitter, allowing the fan to start again.

The next two seconds disappeared in a chaos of hope and fear. The fan restarted, the blades reaching maximum speed almost at once. Alex felt the breath being knocked out of him as his back and shoulders slammed into the pipe. Out of the corner of his eye, he saw the viper above him, its eyes blazing, its mouth stretched open to reveal its curved fangs. The snake landed on him, its head on his chest, and Alex squirmed, barely able to stop himself from crying out in horror. Something splashed into his face. It tasted foul on his lips. He waited for the snake to bite him, but it had twisted away, as if more interested in something else. Another two seconds passed and in that time he saw that his plan had worked, that he hadn’t been bitten. The fan had cut the saw-scaled viper in half. More accurately, about five inches had made it through. The other fifteen had been left behind. Some sort of signal must have reached whatever brain it had, but it had lost interest in Alex, staring back at its own remains. Alex backed away, moving like a crab on the palms of his hands and the soles of his feet. He was feeling sick. He reached up with one arm and used his sleeve to wipe the snake’s blood off his face. The viper was no longer moving. Finally, Alex reached for his water bottle and emptied it in three large gulps.

Snakes—and spiders—have a power that’s hard to define. It’s primal. When one comes close, human beings will react in the same way as any animal, and that was what had happened to Alex. He had been submerged in pure, instinctive terror, and it took him several minutes to recover, all the time staring at the severed head and the red, bleeding stub, wondering if the creature was really dead. Only when his heart was beating normally did he turn the transmitter back on, deactivating the fan once again. Then, carefully, he made his way through, trying to ignore the blood splatter on the pipe all around him.

After that, he moved as quickly as possible—both to make up time and to put the nightmare far behind him.

“When you get through the exhaust fan, there’s about a hundred yards. It’s pretty level and you should have nothing to worry about until you get to the main air shaft. That’s when things begin to get interesting.”

Smithers’s voice guided Alex as he continued forward. The pipe was large enough to allow him to move freely, but he still felt the weight of the mountain, the intense darkness, the loneliness, and he had to fight to stay focused, to breathe normally. He had remembered to turn the fan back on before he left. He didn’t want a maintenance engineer turning up to see what was wrong. Ahead of him he was aware of a soft beating sound, some sort of machinery. He knew that he was getting close to the end.

“The plans show that the air shaft drops vertically—six hundred feet. That’s about the height of the Gherkin in London. It’s one hell of a drop, but unfortunately it’s polished steel, so you can’t climb down. It’s too far to lower you on a rope. And I’m afraid it’s not quite wide enough for a parachute.”

“So what do I do?”

“That’s a very good question, Alex.”

Alex reached the edge of the air shaft. The ground had opened up beneath him and he lay, stretched out on his stomach, gazing down into nothingness. The beam of his headlamp was nowhere near powerful enough to reach the bottom and simply stopped in midair, illuminating the metal circle around it. The height of the Gherkin. It was as if he were lying on the roof of a London skyscraper, thinking about throwing himself off. Smithers had assured him that he had a plan and that it would work, but Alex could only take his word for it. Was he reliable?

Well, there was only one way to find out. Alex swallowed hard, then reached behind him and found a cable poking out of his backpack. It had a jack plug that clicked into a socket built into one of the shoulders of his combat suit. He turned it and heard the safety lock engage. Then he waited for the computer that he had carried all this distance to boot up and do its work. Smithers had said it would only take five seconds, but he waited half a minute just to be sure.

This was worse than the snake. What he was about to do went against every instinct. It was like committing suicide. But there was no other way.

Alex swung himself around and threw himself into the void.
    </p>

    < ChapterFooter />
    </div>
  )
}

export default Chapter2